### ISSUE TITLE
통합 검색 페이지 구현

### ISSUE THREAD

**Issue by yeonc** [yeonc/fapiz-frontend#22]
## To-do
- [x] 검색 창 영역
- [x] 검색 결과 영역
  - [x] SNS 게시물 검색 결과
  - [x] 유저 검색 결과

**Comment by yeonc** [comment]
## 회고 💬
### good 👍
검색 페이지를 구현하기 전에 간단하게라도 나름대로의 틀을 세우고 들어갔던 게 제일 잘한 일 같다.
불명확한 계획을 세웠을 때는, 구현하는 중간에도 생각이 왔다갔다거려서 어떻게 해야 할지 잘 모르겠다는 느낌을 많이 받았었는데,
미리 컴포넌트도 나누고 컴포넌트들의 역할도 생각해 두고 기능 관련된 사항들도 최대한 명확히 정의한 뒤에 작업을 시작했더니
구현할 때 확실히 덜 헤매게 되고, 구현하는 과정 자체도 그냥 막연함만 가지고 덤빌 때보다는 훨씬 원활하게 진행된다는 느낌을 받았다.
아쉬운 부분이 없었던 건 아니지만, 핵심적인 것들은 다 구현했으니 만족한다.

### bad 👎
요즘 체력관리를 하기가 너무 힘든 것 같다.
내가 먼저 무리하지 않는 게 제일 중요하지만, 그것과는 상관없이 지치는 경우도 많은 것 같다.
조금만 더 힘내보자!
